# Dockerfile para o Cliente de Jogo
# Item 9: Emprego do Docker e Emulação Realista

FROM golang:1.21-alpine

WORKDIR /app

# Pré-instalação de dependências para evitar reinstalação a cada mudança de código
COPY go.mod go.sum ./
RUN go mod download

# Copia o código-fonte da aplicação
COPY *.go ./

# Compila o executável do cliente
RUN go build -o /client

# Comando de execução
CMD [ "/client" ]

